version: 0.2
phases:
install:
runtime-versions:
nodejs: 14
commands:
- echo Installing dependencies...
- npm install
pre_build:
commands:
- echo Retrieving secrets...
- |
SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id MyAppSecrets --query SecretString --output text)
export DB_USER=$(echo $SECRET_JSON | jq -r .DB_USER)
export DB_PASS=$(echo $SECRET_JSON | jq -r .DB_PASS)
build:
commands:
- echo Building the app...
- npm run build || echo "No build step"
post_build:
commands:
- echo Build complete.
artifacts:
files:
- '**/*'
